import { loadData } from "./data.js";
import { validateData } from "./validate.js";
import { createReaderProgress, getCanonicalReaderState, getRelevantHistoricalWiki, setCanonicalReaderState, subscribeCanonicalReaderState } from "./reader-progress.js";

const chapterInput=document.querySelector("#chapter"),chapterApply=document.querySelector("#chapter-apply"),prevButton=document.querySelector("#prev-section"),nextButton=document.querySelector("#next-section"),sectionSelect=document.querySelector("#section-select"),bookLabel=document.querySelector("#book-label"),title=document.querySelector("#section-title"),status=document.querySelector("#status"),characterList=document.querySelector("#character-list"),eventList=document.querySelector("#event-list"),wikiList=document.querySelector("#wiki-list"),validation=document.querySelector("#validation"),characterFilters=document.querySelector("#character-filters"),placeLegend=document.querySelector("#place-legend"),selectAll=document.querySelector("#select-all"),selectNone=document.querySelector("#select-none"),characterToggle=document.querySelector("#character-toggle"),characterFilterBody=document.querySelector("#character-filter-body");
const placeLegendGroups=[
  {types:["exact_site"],label:"Sito preciso",iconType:"literary_landmark"},
  {types:["urban_area","settlement"],label:"Città / insediamento",iconType:"city"},
  {types:["settlement_area"],label:"Villaggio",iconType:"village"},
  {types:["area","region"],label:"Area / regione",iconType:"area"},
  {types:["river"],label:"Fiume",iconType:"river"},
  {types:["route","bridge"],label:"Percorso / ponte",iconType:"route"},
  {types:["temple"],label:"Tempio",iconType:"temple"},
  {types:["castle","fortified_site"],label:"Castello / fortificazione",iconType:"castle"},
  {types:["narrative_site","literary_landmark"],label:"Luogo narrativo",iconType:"literary_landmark"}
];
const iconPaths={temple:"assets/icons/places/temple.svg",castle:"assets/icons/places/castle.svg",city:"assets/icons/places/city.svg",village:"assets/icons/places/village.svg",area:"assets/icons/places/area.svg",river:"assets/icons/places/river.svg",route:"assets/icons/places/route.svg",literary_landmark:"assets/icons/places/landmark.svg"};let data,reader;
function characterDisplayName(character,section){if(character?.id==="musashi"&&section<=8)return "Shinmen Takezō";return character?.name??"Personaggio sconosciuto";}
function applySection(value){if(!reader.setSection(value))return false;const state=getCanonicalReaderState();setCanonicalReaderState({section:reader.section,selectedCharacters:state.selectedCharacters});return true;}
function renderPlaceLegend(){const usedTypes=new Set(data.locations.locations.map(location=>location.type));placeLegend.replaceChildren(...placeLegendGroups.filter(group=>group.types.some(type=>usedTypes.has(type))).map(group=>{const item=document.createElement("div");item.className="legend-item";const swatch=document.createElement("span");swatch.className=`legend-swatch legend-${group.iconType}`;swatch.setAttribute("aria-hidden","true");const image=document.createElement("img");image.src=iconPaths[group.iconType];image.alt="";image.draggable=false;swatch.append(image);const text=document.createElement("span");text.textContent=group.label;item.append(swatch,text);return item;}));}
function renderCharacterFilters(selectedCharacters,section){const mainCharacters=data.characters.characters.filter(c=>c.importance==="main");characterFilters.replaceChildren(...mainCharacters.map((character,index)=>{const label=document.createElement("label");label.className="character-filter";const swatch=document.createElement("span");swatch.className="character-swatch";swatch.style.setProperty("--character-color",characterColors[index%characterColors.length]);swatch.setAttribute("aria-hidden","true");const input=document.createElement("input");input.type="checkbox";input.checked=selectedCharacters.has(character.id);const displayName=characterDisplayName(character,section);input.setAttribute("aria-label",`Segui ${displayName}`);input.addEventListener("change",()=>{const nextSelected=new Set(selectedCharacters);if(input.checked)nextSelected.add(character.id);else nextSelected.delete(character.id);const state=getCanonicalReaderState();setCanonicalReaderState({section:state.section,selectedCharacters:[...nextSelected]});});const name=document.createElement("span");name.textContent=displayName;label.append(swatch,input,name);return label;}));}
function createWikiCard(entry,{character=false}={}){const card=document.createElement("article");card.className=`wiki-card ${character?"character-wiki-card":""}`;const button=document.createElement("button");button.type="button";button.className="wiki-card-toggle";button.setAttribute("aria-expanded","false");const cardTitle=document.createElement("span");cardTitle.className="wiki-card-title";cardTitle.textContent=entry.display_name;const chevron=document.createElement("span");chevron.className="wiki-card-chevron";chevron.setAttribute("aria-hidden","true");chevron.textContent="＋";button.append(cardTitle,chevron);const body=document.createElement("div");body.className="wiki-card-body";body.hidden=true;const role=document.createElement("p");role.className="wiki-trigger";role.textContent=character?entry.role:(entry.novel_trigger?.context??"Riferimento incontrato nel romanzo.");body.append(role);const summary=document.createElement("p");summary.textContent=character?entry.finora:(entry.wiki?.summary??"Contesto storico non disponibile.");body.append(summary);if(character){const currentSections=Object.keys(entry.current_by_section??{}).map(Number).filter(n=>Number.isFinite(n));if(currentSections.length){const currentSection=Math.max(...currentSections);const current=document.createElement("p");current.innerHTML=`<strong>Stato attuale:</strong> ${entry.current_by_section[String(currentSection)]}`;body.append(current);}}if(!character&&entry.source?.url&&entry.source?.status!=="needs_authoritative_source_record"){const source=document.createElement("a");source.className="wiki-source";source.href=entry.source.url;source.target="_blank";source.rel="noopener noreferrer";source.textContent=`${entry.source.publisher??"Fonte"} · fonte storica`;body.append(source);}button.addEventListener("click",()=>{const open=button.getAttribute("aria-expanded")==="true";button.setAttribute("aria-expanded",String(!open));body.hidden=open;card.classList.toggle("is-open",!open);});card.append(button,body);return card;}
function renderHistoricalWiki(entries,nodes){if(!entries.length)return;const heading=document.createElement("h3");heading.className="wiki-subheading";heading.textContent="Contesto storico";nodes.push(heading);entries.forEach(entry=>nodes.push(createWikiCard(entry)));}
function renderSecondaryCharacters(entries,section,nodes){const visible=entries.filter(entry=>entry.category==="secondary"&&Object.keys(entry.current_by_section??{}).some(key=>Number(key)<=section));if(!visible.length)return;const heading=document.createElement("h3");heading.className="wiki-subheading character-wiki-heading";heading.textContent="Personaggi secondari";nodes.push(heading);visible.forEach(entry=>nodes.push(createWikiCard(entry,{character:true})));}
function renderWiki(section){const historicalEntries=getRelevantHistoricalWiki(data.microWiki.entities,section),characterEntries=Object.values(data.characterWiki?.characters??{}),nodes=[];renderSecondaryCharacters(characterEntries,section,nodes);renderHistoricalWiki(historicalEntries,nodes);if(!nodes.length){const empty=document.createElement("p");empty.className="wiki-empty";empty.textContent="Nessun personaggio secondario o riferimento storico rilevante nelle sezioni già lette.";nodes.push(empty);}wikiList.replaceChildren(...nodes);}
function render(){if(!data||!reader)return;const readerState=getCanonicalReaderState(),section=readerState.section,selectedCharacters=new Set(readerState.selectedCharacters),sectionData=data.chapters.sections.find(s=>s.number===section);if(!sectionData)return;bookLabel.textContent=sectionData.book_title;title.textContent=sectionData.title;status.textContent=`Sezione ${section} · informazioni visibili fino a questo punto della storia`;sectionSelect.value=String(section);chapterInput.value=String(section);prevButton.disabled=section<=reader.min;nextButton.disabled=section>=reader.max;const characterById=new Map(data.characters.characters.map(c=>[c.id,c])),locationById=new Map(data.locations.locations.map(l=>[l.id,l])),states=reader.visibleLatestStates(data.states.character_states),visibleStates=states.filter(s=>selectedCharacters.has(s.character));characterList.replaceChildren(...visibleStates.map(s=>{const card=document.createElement("article"),character=characterById.get(s.character),location=locationById.get(s.location);card.innerHTML=`<h3>${characterDisplayName(character,section)}</h3><p><strong>${location?.name??"Posizione non determinata"}</strong></p><p>${s.activity}</p><small>Presenza: ${s.presence??s.status}; confidenza luogo: ${s.location_confidence??s.certainty}</small>`;return card;}));const events=data.events.events.filter(e=>e.section===section&&e.characters.some(id=>selectedCharacters.has(id)));eventList.replaceChildren(...events.map(e=>{const item=document.createElement("li"),names=e.characters.map(id=>characterDisplayName(characterById.get(id),section)).join(", "),from=e.origin?locationById.get(e.origin)?.name:null,to=e.destination?locationById.get(e.destination)?.name:null,place=e.location?locationById.get(e.location)?.name:null;item.textContent=`${names}: ${e.type}${from&&to?` · ${from} → ${to}`:place?` · ${place}`:""}`;return item;}));renderCharacterFilters(selectedCharacters,section);renderWiki(section);}
subscribeCanonicalReaderState(()=>render());
try{data=await loadData();reader=createReaderProgress(data.chapters,data.readerProgress.state.current_section);const result=validateData(data);validation.textContent=result.valid?"Database: validato":`Database: ${result.errors.length} errori`;validation.dataset.state=result.valid?"ok":"error";if(result.errors.length)console.error("MusashiMap data validation errors",result.errors);chapterInput.min=String(reader.min);chapterInput.max=String(reader.max);sectionSelect.replaceChildren(...data.chapters.sections.map(s=>{const option=document.createElement("option");option.value=String(s.number);option.textContent=`${s.book} — ${s.title}`;return option;}));renderPlaceLegend();const initialState=getCanonicalReaderState(),initialSection=initialState.section??reader.section,initialSelected=initialState.selectedCharacters.length?initialState.selectedCharacters:data.characters.characters.filter(c=>c.importance==="main").map(c=>c.id);setCanonicalReaderState({section:initialSection,selectedCharacters:initialSelected});}catch(error){validation.textContent="Errore nel caricamento dei dati";console.error(error);}
chapterInput.addEventListener("input",()=>{chapterInput.setCustomValidity("");if(chapterInput.value==="")return;const parsed=Number.parseInt(chapterInput.value,10);if(!Number.isInteger(parsed)||parsed<reader.min||parsed>reader.max)chapterInput.setCustomValidity(`Inserisci una sezione da ${reader.min} a ${reader.max}.`);});chapterInput.addEventListener("keydown",event=>{if(event.key==="Enter"){if(!applySection(chapterInput.value))chapterInput.reportValidity();}else if(event.key==="Escape")chapterInput.value=String(getCanonicalReaderState().section);});chapterApply.addEventListener("click",()=>{if(!applySection(chapterInput.value))chapterApply.reportValidity();});prevButton.addEventListener("click",()=>{if(reader.previous())applySection(reader.section);});nextButton.addEventListener("click",()=>{if(reader.next())applySection(reader.section);});sectionSelect.addEventListener("change",()=>applySection(sectionSelect.value));selectAll.addEventListener("click",()=>{const selectedCharacters=data.characters.characters.filter(c=>c.importance==="main").map(c=>c.id),state=getCanonicalReaderState();setCanonicalReaderState({section:state.section,selectedCharacters});});selectNone.addEventListener("click",()=>{const state=getCanonicalReaderState();setCanonicalReaderState({section:state.section,selectedCharacters:[]});});characterToggle.addEventListener("click",()=>{const isOpen=characterToggle.getAttribute("aria-expanded")==="true";characterToggle.setAttribute("aria-expanded",String(!isOpen));characterToggle.textContent=isOpen?"Mostra filtri":"Nascondi filtri";characterFilterBody.hidden=isOpen;});