import { mergeNewlyVisibleSelection } from "./character-selection.js";
import { loadData } from "./data.js";
import { getPlaceLegendEntries } from "./place-presentation.js";
import { createReaderProgress, getCanonicalReaderState, getDisplayCharacterName, getPositionStatusLabel, getProgressiveDisplayName, getProgressiveValue, getReaderSnapshot, getRelevantHistoricalWiki, getVisibleCharacters, resolveCharacterPosition, setCanonicalReaderState, subscribeCanonicalReaderState } from "./reader-progress.js";

const chapterInput=document.querySelector("#chapter"),chapterApply=document.querySelector("#chapter-apply"),prevButton=document.querySelector("#prev-section"),nextButton=document.querySelector("#next-section"),sectionSelect=document.querySelector("#section-select"),bookLabel=document.querySelector("#book-label"),title=document.querySelector("#section-title"),status=document.querySelector("#status"),characterList=document.querySelector("#character-list"),eventList=document.querySelector("#event-list"),wikiList=document.querySelector("#wiki-list"),dataStatus=document.querySelector("#data-status"),characterFilters=document.querySelector("#character-filters"),placeLegend=document.querySelector("#place-legend"),selectAll=document.querySelector("#select-all"),selectNone=document.querySelector("#select-none"),characterToggle=document.querySelector("#character-toggle"),characterFilterBody=document.querySelector("#character-filter-body");
let data,reader,furthestSectionReached=null;
function applySection(value){if(!reader.setSection(value))return false;const state=getCanonicalReaderState(),nextSection=reader.section,previouslyVisible=getVisibleMainCharacters(furthestSectionReached).map(character=>character.id),currentlyVisible=getVisibleMainCharacters(nextSection).map(character=>character.id),selectedCharacters=nextSection>furthestSectionReached?mergeNewlyVisibleSelection(previouslyVisible,currentlyVisible,state.selectedCharacters):state.selectedCharacters;furthestSectionReached=Math.max(furthestSectionReached,nextSection);setCanonicalReaderState({section:nextSection,selectedCharacters});return true;}
function renderPlaceLegend(){const mappedTypes=data.locations.locations.filter(location=>Array.isArray(location.coordinates)&&location.coordinates.length===2).map(location=>location.type);placeLegend.replaceChildren(...getPlaceLegendEntries(mappedTypes).map(presentation=>{const item=document.createElement("div");item.className="legend-item";const swatch=document.createElement("span");swatch.className="legend-swatch";swatch.setAttribute("aria-hidden","true");const image=document.createElement("img");image.src=presentation.iconPath;image.alt="";image.draggable=false;swatch.append(image);const text=document.createElement("span");text.textContent=presentation.legendLabel;item.append(swatch,text);return item;}));}
function getVisibleMainCharacters(section){return getVisibleCharacters(data.characters.characters,section,{states:data.states.character_states,events:data.events.events,characterWiki:data.characterWiki?.characters}).filter(character=>character.importance==="main");}
function renderCharacterFilters(selectedCharacters,section){const mainCharacters=getVisibleMainCharacters(section);characterFilters.replaceChildren(...mainCharacters.map(character=>{const label=document.createElement("label");label.className="character-filter";const swatch=document.createElement("span");swatch.className="character-swatch";swatch.style.setProperty("--character-color",character.color);swatch.setAttribute("aria-hidden","true");const input=document.createElement("input");input.type="checkbox";input.checked=selectedCharacters.has(character.id);const displayName=getDisplayCharacterName(character,section,data.identities?.identities);input.setAttribute("aria-label",`Segui ${displayName}`);input.addEventListener("change",()=>{const nextSelected=new Set(selectedCharacters);if(input.checked)nextSelected.add(character.id);else nextSelected.delete(character.id);const state=getCanonicalReaderState();setCanonicalReaderState({section:state.section,selectedCharacters:[...nextSelected]});});const name=document.createElement("span");name.className="character-filter-name";name.textContent=displayName;label.append(swatch,input,name);return label;}));}
function getStateLocationPresentation(state,locationById){
  const resolved=resolveCharacterPosition(state,locationById),location=resolved.referencedLocation;
  return {label:location?.name??"Posizione non determinata",meta:location?getPositionStatusLabel(resolved.mode):"Posizione non determinata"};
}
function createWikiCard(entry,{character=false,section=1}={}){const card=document.createElement("article");card.className=`wiki-card ${character?"character-wiki-card":""}`;const button=document.createElement("button");button.type="button";button.className="wiki-card-toggle";button.setAttribute("aria-expanded","false");const cardTitle=document.createElement("span");cardTitle.className="wiki-card-title";cardTitle.textContent=character?getProgressiveDisplayName(entry,section):entry.display_name;const chevron=document.createElement("span");chevron.className="wiki-card-chevron";chevron.setAttribute("aria-hidden","true");chevron.textContent="＋";button.append(cardTitle,chevron);const body=document.createElement("div");body.className="wiki-card-body";body.hidden=true;const role=document.createElement("p");role.className="wiki-trigger";role.textContent=character?entry.role:(entry.novel_trigger?.context??"Riferimento incontrato nel romanzo.");body.append(role);const summary=document.createElement("p");const progressiveText=character?getProgressiveValue(entry.current_by_section,section):null;summary.textContent=progressiveText??(character?entry.role:(entry.wiki?.summary??"Contesto storico non disponibile."));body.append(summary);if(!character&&entry.source?.url&&entry.source?.status!=="needs_authoritative_source_record"){const source=document.createElement("a");source.className="wiki-source";source.href=entry.source.url;source.target="_blank";source.rel="noopener noreferrer";source.textContent=`${entry.source.publisher??"Fonte"} · fonte storica`;body.append(source);}button.addEventListener("click",()=>{const open=button.getAttribute("aria-expanded")==="true";button.setAttribute("aria-expanded",String(!open));body.hidden=open;card.classList.toggle("is-open",!open);});card.append(button,body);return card;}
function renderHistoricalWiki(entries,nodes,section){const heading=document.createElement("h3");heading.className="wiki-subheading";heading.textContent="Contesto storico";nodes.push(heading);entries.forEach(entry=>nodes.push(createWikiCard(entry,{section})));}
function renderSecondaryCharacters(entries,section,nodes){const visible=entries.filter(entry=>entry.category==="secondary"&&Object.keys(entry.current_by_section??{}).some(key=>Number(key)<=section));if(!visible.length)return;const heading=document.createElement("h3");heading.className="wiki-subheading character-wiki-heading";heading.textContent="Personaggi secondari";nodes.push(heading);visible.forEach(entry=>nodes.push(createWikiCard(entry,{character:true,section})));}
function renderWiki(section){const historicalEntries=getRelevantHistoricalWiki(data.microWiki.entities,section),characterEntries=Object.values(data.characterWiki?.characters??{}),nodes=[];renderSecondaryCharacters(characterEntries,section,nodes);renderHistoricalWiki(historicalEntries,nodes,section);if(!nodes.length){const empty=document.createElement("p");empty.className="wiki-empty";empty.textContent="Nessun personaggio secondario o riferimento storico rilevante nelle sezioni già lette.";nodes.push(empty);}wikiList.replaceChildren(...nodes);}
function render(){if(!data||!reader)return;const readerState=getCanonicalReaderState(),section=readerState.section,visibleMainCharacters=getVisibleMainCharacters(section),visibleIds=new Set(visibleMainCharacters.map(character=>character.id)),selectedCharacters=new Set(readerState.selectedCharacters.filter(id=>visibleIds.has(id))),sectionData=reader.sections.find(s=>s.number===section);if(!sectionData)return;bookLabel.textContent=sectionData.book_title;title.textContent=sectionData.title;status.textContent=`Sezione ${section} · informazioni visibili fino a questo punto della storia`;sectionSelect.value=String(section);chapterInput.value=String(section);prevButton.disabled=section<=reader.min;nextButton.disabled=section>=reader.max;const characterById=new Map(data.characters.characters.map(c=>[c.id,c])),locationById=new Map(data.locations.locations.map(l=>[l.id,l])),snapshot=getReaderSnapshot({states:data.states.character_states,events:data.events.events},section,selectedCharacters);characterList.replaceChildren(...snapshot.selectedStates.map(s=>{const card=document.createElement("article"),character=characterById.get(s.character),presentation=getStateLocationPresentation(s,locationById);card.innerHTML=`<h3>${getDisplayCharacterName(character,section,data.identities?.identities)}</h3><p><strong>${presentation.label}</strong></p><p>${s.activity}</p><small>Stato: ${presentation.meta} · confidenza: ${s.location_confidence??s.certainty}</small>`;return card;}));eventList.replaceChildren(...snapshot.sectionEvents.map(e=>{const item=document.createElement("li");item.textContent=e.description??"";return item;}));renderCharacterFilters(selectedCharacters,section);renderWiki(section);}
subscribeCanonicalReaderState(()=>render());
try{data=await loadData();reader=createReaderProgress(data.chapters,data.readerProgress);dataStatus.textContent="Dati caricati";dataStatus.dataset.state="ok";chapterInput.min=String(reader.min);chapterInput.max=String(reader.max);sectionSelect.replaceChildren(...reader.sections.map(s=>{const option=document.createElement("option");option.value=String(s.number);option.textContent=`${s.book} — ${s.title}`;return option;}));renderPlaceLegend();const initialState=getCanonicalReaderState();if(initialState.section!==null)reader.setSection(initialState.section);const initialSection=reader.section,visibleIds=new Set(getVisibleMainCharacters(initialSection).map(character=>character.id)),initialSelected=initialState.selectedCharacters.length?initialState.selectedCharacters.filter(id=>visibleIds.has(id)):[...visibleIds];furthestSectionReached=initialSection;setCanonicalReaderState({section:initialSection,selectedCharacters:initialSelected});}catch(error){dataStatus.textContent="Errore nel caricamento dei dati";dataStatus.dataset.state="error";console.error(error);}
chapterInput.addEventListener("input",()=>{chapterInput.setCustomValidity("");if(chapterInput.value==="")return;const parsed=Number.parseInt(chapterInput.value,10);if(!reader.sections.some(section=>section.number===parsed))chapterInput.setCustomValidity(`Inserisci una sezione disponibile da ${reader.min} a ${reader.max}.`);});chapterInput.addEventListener("keydown",event=>{if(event.key==="Enter"){if(!applySection(chapterInput.value))chapterInput.reportValidity();}else if(event.key==="Escape")chapterInput.value=String(getCanonicalReaderState().section);});chapterApply.addEventListener("click",()=>{if(!applySection(chapterInput.value))chapterInput.reportValidity();});prevButton.addEventListener("click",()=>{if(reader.previous())applySection(reader.section);});nextButton.addEventListener("click",()=>{if(reader.next())applySection(reader.section);});sectionSelect.addEventListener("change",()=>applySection(sectionSelect.value));selectAll.addEventListener("click",()=>{const state=getCanonicalReaderState(),selectedCharacters=getVisibleMainCharacters(state.section).map(character=>character.id);setCanonicalReaderState({section:state.section,selectedCharacters});});selectNone.addEventListener("click",()=>{const state=getCanonicalReaderState();setCanonicalReaderState({section:state.section,selectedCharacters:[]});});
